# Generated by Django 4.1.3 on 2022-11-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_follow_user_followed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user_who_followed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user_who_liked',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
