# Generated by Django 4.1.3 on 2022-11-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_follow_user_who_followed_alter_likes_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.JSONField(null=True),
        ),
    ]
