# Generated by Django 4.1.3 on 2022-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default=b'$2b$12$BsUKp0nnh1GaQL0NmnVpRu', max_length=255),
        ),
    ]
