# Generated by Django 4.1.3 on 2022-11-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_salt',
            field=models.CharField(default=b'$2b$12$GWoP7T.ed9oK.i5TV99Uqe', max_length=255),
        ),
    ]
